###
localhost:8080/jws-hmac/hs256/token

###
localhost:8080/jws-hmac/hs256/verify?token=eyJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiOGFlYjdmYWMtNGY2ZS00ZGM5LWI5MDYtNWYwZjYwMjk1YzMxIiwicHdkIjoiSXZhbiBSaXpreWFudG8ifQ.sbyactWg32mmtQ_XCjjreKpJBSgvqDmMEDGiyuJ8K-I

###
localhost:8080/jws-rsa/rs256/token

###
localhost:8080/jws-rsa/rs256/verify?token=eyJlbmMiOiJBMTI4R0NNIiwiYWxnIjoiUlNBLU9BRVAtMjU2In0.ij21kXczg72nIbtIgsOAcnu6mDznmS89ATeIcAnI0EyCz1Yxr_M6Ou1SP1Qu8loDeF0VGjngEHwNWRdwOnA0LFN-uNd7_NngbjZeIrzImpcNh3BQvRbnF_Yixz9jflVuR-_wsWZmuQKw4_-iJ4I-ke4l_TA5Eh-8ouScpE2UbXnxqedsfb2Xq2i6M_IWzbk06MufKSQ7_dEKCRFR9FAdYnZwWon5MpZkxtx8gGZgABW4jgg36ETqju3MPoQB3XMei41H2tjuG0roxbEabba_qrBRXU8eaHANLr9oBUTpsSYEdBiPK7KOxeKm9FgJArlc8cHn4_Jt-ccUHylGoQCc2A.-W15rs0xd0SVeUvV.FQRVlQ3hLAqAgzLUrcgNz7h3zaMK5RLON5CE77Ci64EIVo527qS5_Mv0ovXOS5dhcaGnl7SyXwCMkqFvv4BilWBEZT70LqMh8oPiKWBipiDKQIIPeRh1SdvxO41WYbnpsqBXtZeecIQETXUdqyP7tHmFYbQl8WK2xzpAwzGVgqKRGRTTglo4xahSbvgUQRXk60fGwS46_5-hMyZBeVmxQJLliH9N8rhO.UNisXCpagyBSwpOP-ph7Ew

###
localhost:8080/jwt-rsa/rs256/token

###
localhost:8080/jwt-rsa/rs256/verify?token=eyJraWQiOiIwZGE5YmNjYS0yNGRiLTQwY2MtYWZjYy02MWMzZDBjMTMxMmYiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIyYWM2Y2JmZC00ZjZkLTQzODEtODllNC0wZWVkOGQ5MTdjZGQiLCJhdWQiOiJzZWxmIiwibmJmIjoxNzI1MzQ5Njk3LCJpc3MiOiJzZWxmIiwiZXhwIjoxODI1MzU5NzU3LCJpYXQiOjE3MjUzNDk2OTcsImp0aSI6IjZhZTFiODM0LWE0MTQtNDk2ZC1iMGFiLTNmMmY1NDMzNzUzMyIsInB3ZCI6Ikl2YW4gUml6a3lhbnRvIn0.xaT4s3e0N-dqk7pduOLCHuTP3iXIYkkSFYdF5zb4RWycC02_EXzM3x_8BCJzFarPTWEcDYkrNbWlgTKaQCmf08bH2Lkm6s4tlGeJ31mnPloyZ9e8OFX8d4j3Sh2q-OExFV0iLyp0LBxEXVCnqYp7gg9aeYmnBb5zzzYyIFSqXXGFtD14ptZV0c9ZSPSNr4lPuKomyo4Ifi-3QmPP7MMG6No_uNjiZO76JXH-pCxzcr_As4yQbY4sZEamy8bcLDqJL77_aYVQoMVVfVBPR15XCv4Yx_yVZpzAgzBbxK9qyNd9ZDRpGIKFzdQ62Vbg0P-kVx9Yt2KSkszsd90vWef0PQ

###
localhost:8080/jwe-rsa/rsa-oaep-256/token

###
localhost:8080/jwe-rsa/rsa-oaep-256/verify?token=eyJlbmMiOiJBMTI4R0NNIiwiYWxnIjoiUlNBLU9BRVAtMjU2In0.Dh4n4qnImfmnQLDIhbhm0UF3ei8GohOOkMs5PoSrSchLhL-EqiThgELDaIhfKlsGlRolhGbInogNyc89WnN57Vb_69dQLVa63EPT5vKMePuUtt6A8hi5CPLzcfZi-i1jhZD6D_qyPD2xstLPFnK230A4UiWOqKey4tzD8DiLoy1sxBOmxQLSMQw_1-Vn02TdWM8wKjnJ18Muld87GAvuse9HqidSZeh4aFUFw7kngTSs85Jsiqcq1xCF6JMtfgObmdVFnpDhAIzy1Bf_BNUrjfvbniY_Vc4GVO7vA-DveI89fnq2qceSqxI_j8NzH5-gKBSqBVS98Tf9lnDPPz5Uaw.O2oQJoVbKiOslfZC.HbH1vfL4XVfrj5enqXdo9F2MOzCboGsSAC8IMfGfgpMuv4drP740dDki9u6vIGgq56koZ5KUa0-HNLfnc2IrWKm6b52Rri3Xc1AHKigdfaAQ7Cf1jI2Y_KsuQ_c8c0SkcfaOskjFFAFU_SoCxVweeVpU66NI4qqX0MTMgmG2HUhl6CFmOsnK4qGuPQnTC9eeMNvUkddapTLI_IeCuiJPNkl4sYRKo14F.BDACoQNKureBizo0bq3xuA
